print("My name is Viswanadha Hemasri")
print("My father name is V.S.V.S.satyanarayana")
print("My mother name is V.N.V.Rajyalakshmi")
print("I am studying BCA-3rd sem in ADCSKLM")
print("My habits are listening to music,watching T.V")
print("I am interested in arts and cooking")
print("my favouraite colour is blue")